import { auth, db, collection, addDoc, onSnapshot, doc, updateDoc, deleteDoc, serverTimestamp, signInWithEmailAndPassword, createUserWithEmailAndPassword, onAuthStateChanged, signOut, setDoc, getDoc } from './firebase-config.js';
const $=id=>document.getElementById(id);
const els={authScreen:$('authScreen'),mainShell:$('mainShell'),loginForm:$('loginForm'),loginEmail:$('loginEmail'),loginPassword:$('loginPassword'),registerBtn:$('registerBtn'),pinScreen:$('pinScreen'),pinInput:$('pinInput'),pinBtn:$('pinBtn'),backToLoginBtn:$('backToLoginBtn'),authSyncBadge:$('authSyncBadge'),syncBadge:$('syncBadge'),logoutBtn:$('logoutBtn'),authBusinessName:$('authBusinessName'),headerBusinessName:$('headerBusinessName'),headerUserEmail:$('headerUserEmail'),appointmentForm:$('appointmentForm'),appointmentId:$('appointmentId'),clientName:$('clientName'),clientPhone:$('clientPhone'),service:$('service'),price:$('price'),date:$('date'),time:$('time'),barber:$('barber'),status:$('status'),notes:$('notes'),formTitle:$('formTitle'),saveBtn:$('saveBtn'),resetBtn:$('resetBtn'),filterDate:$('filterDate'),todayCount:$('todayCount'),todayRevenue:$('todayRevenue'),completedCount:$('completedCount'),completedRevenue:$('completedRevenue'),pendingCount:$('pendingCount'),confirmedCount:$('confirmedCount'),noshowCount:$('noshowCount'),timeline:$('timeline'),clientsList:$('clientsList'),servicesList:$('servicesList'),serviceForm:$('serviceForm'),serviceId:$('serviceId'),serviceName:$('serviceName'),servicePrice:$('servicePrice'),serviceTime:$('serviceTime'),resetServiceBtn:$('resetServiceBtn'),settingsForm:$('settingsForm'),businessName:$('businessName'),businessPin:$('businessPin'),quickAddBtn:$('quickAddBtn'),toast:$('toast')};
let currentUser=null,appointments=[],services=[],settings={businessName:'Nexus Salón',pin:'2026'},unsubAppointments=null;
const today=new Date().toISOString().slice(0,10); els.date.value=today; els.filterDate.value=today;
const fallbackServices=[{id:'srv1',name:'Corte clásico',price:20,time:'30 min'},{id:'srv2',name:'Fade premium',price:30,time:'40 min'},{id:'srv3',name:'Barba',price:18,time:'20 min'},{id:'srv4',name:'Corte + Barba',price:40,time:'50 min'}];
const toast=msg=>{els.toast.textContent=msg;els.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.add('hidden'),2600);};
const money=v=>new Intl.NumberFormat('es-PR',{style:'currency',currency:'USD'}).format(v||0);
const esc=(s='')=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'","&#039;");
const statusClass=s=>`status-${(s||'').toLowerCase().replace(/\s+/g,'-')}`;
const sortAppointments=items=>[...items].sort((a,b)=>`${a.date||''} ${a.time||''}`.localeCompare(`${b.date||''} ${b.time||''}`));
function activateView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelector(`#view-${view}`)?.classList.add('active');document.querySelectorAll('.nav-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.view===view));}
function setSyncState(mode,text){const cls=mode==='ok'?'sync-ok':mode==='error'?'sync-error':'sync-loading';[els.syncBadge,els.authSyncBadge].forEach(el=>{el.className=`sync-badge ${cls}`;el.textContent=text;});}
function applyBranding(){els.authBusinessName.textContent=settings.businessName;els.headerBusinessName.textContent=settings.businessName;els.businessName.value=settings.businessName;els.businessPin.value=settings.pin;}
function renderServiceOptions(){els.service.innerHTML=['<option value="">Selecciona</option>'].concat(services.map(s=>`<option value="${esc(s.name)}" data-price="${s.price}">${esc(s.name)}</option>`)).join('');}
function renderServices(){els.servicesList.innerHTML=services.map(s=>`<article class="list-card"><div class="list-title">${esc(s.name)}</div><div class="list-meta">${money(s.price)} · ${esc(s.time)}</div><div class="list-actions"><button class="btn btn-secondary service-edit" data-id="${s.id}">Editar</button><button class="btn btn-danger service-delete" data-id="${s.id}">Borrar</button></div></article>`).join('')||'<div class="list-meta">Sin servicios.</div>';document.querySelectorAll('.service-edit').forEach(b=>b.addEventListener('click',()=>editService(b.dataset.id)));document.querySelectorAll('.service-delete').forEach(b=>b.addEventListener('click',()=>deleteService(b.dataset.id)));}
function renderClients(items){const map=new Map();items.forEach(i=>{const k=`${i.clientName}__${i.clientPhone}`;if(!map.has(k))map.set(k,{name:i.clientName,phone:i.clientPhone,visits:0,spent:0});const r=map.get(k);r.visits++;if(!['Cancelada','No-show'].includes(i.status))r.spent+=Number(i.price||0);});const clients=[...map.values()].sort((a,b)=>b.spent-a.spent);els.clientsList.innerHTML=clients.map(c=>`<article class="list-card"><div class="list-title">${esc(c.name||'Cliente')}</div><div class="list-meta">${esc(c.phone||'Sin teléfono')}</div><div class="list-meta">${c.visitas||c.visits} visitas · ${money(c.spent)}</div></article>`).join('')||'<div class="list-meta">Sin clientes.</div>';}
function renderTimeline(items){if(!items.length){els.timeline.innerHTML='<div class="list-meta">Sin citas para esta fecha.</div>';return;}els.timeline.innerHTML=items.map(i=>`<article class="timeline-item"><div class="timeline-top"><div><div class="timeline-title">${esc(i.time||'--:--')} · ${esc(i.service||'Servicio')}</div><div class="timeline-meta">${esc(i.clientName||'Cliente')} · ${esc(i.barber||'Sin asignar')}</div></div><span class="status-chip ${statusClass(i.status)}">${esc(i.status||'Pendiente')}</span></div><div class="timeline-meta">${esc(i.clientPhone||'Sin teléfono')} · ${money(i.price||0)}${i.notes?`<br>${esc(i.notes)}`:''}</div><div class="timeline-actions"><button class="btn btn-secondary appt-edit" data-id="${i.id}">Editar</button><button class="btn btn-danger appt-delete" data-id="${i.id}">Borrar</button><button class="btn btn-secondary appt-status" data-id="${i.id}" data-status="Completada">Completar</button></div></article>`).join('');document.querySelectorAll('.appt-edit').forEach(b=>b.addEventListener('click',()=>editAppointment(b.dataset.id)));document.querySelectorAll('.appt-delete').forEach(b=>b.addEventListener('click',()=>deleteAppointment(b.dataset.id)));document.querySelectorAll('.appt-status').forEach(b=>b.addEventListener('click',()=>updateAppointmentStatus(b.dataset.id,b.dataset.status)));}
function renderDashboard(){const selected=els.filterDate.value||today,ordered=sortAppointments(appointments),dayItems=ordered.filter(a=>a.date===selected),completed=dayItems.filter(a=>a.status==='Completada'),pending=dayItems.filter(a=>a.status==='Pendiente'),confirmed=dayItems.filter(a=>a.status==='Confirmada'),noShow=dayItems.filter(a=>a.status==='No-show'),totalRevenue=dayItems.filter(a=>!['Cancelada','No-show'].includes(a.status)).reduce((s,a)=>s+Number(a.price||0),0),completedRevenue=completed.reduce((s,a)=>s+Number(a.price||0),0);els.todayCount.textContent=String(dayItems.length);els.todayRevenue.textContent=money(totalRevenue);els.completedCount.textContent=String(completed.length);els.completedRevenue.textContent=money(completedRevenue);els.pendingCount.textContent=String(pending.length);els.confirmedCount.textContent=String(confirmed.length);els.noshowCount.textContent=String(noShow.length);renderTimeline(dayItems);renderClients(ordered);renderServices();}
const resetAppointmentForm=()=>{els.appointmentForm.reset();els.appointmentId.value='';els.formTitle.textContent='Nueva cita';els.saveBtn.textContent='Guardar cita';els.date.value=today;};
const resetServiceForm=()=>{els.serviceForm.reset();els.serviceId.value='';};
function editAppointment(id){const i=appointments.find(a=>a.id===id);if(!i)return;els.appointmentId.value=i.id;els.clientName.value=i.clientName||'';els.clientPhone.value=i.clientPhone||'';els.service.value=i.service||'';els.price.value=i.price||'';els.date.value=i.date||today;els.time.value=i.time||'';els.barber.value=i.barber||'';els.status.value=i.status||'Pendiente';els.notes.value=i.notes||'';els.formTitle.textContent='Editar cita';els.saveBtn.textContent='Actualizar cita';activateView('agenda');}
function editService(id){const i=services.find(s=>s.id===id);if(!i)return;els.serviceId.value=i.id;els.serviceName.value=i.name;els.servicePrice.value=i.price;els.serviceTime.value=i.time;activateView('servicios');}
async function updateAppointmentStatus(id,status){try{await updateDoc(doc(db,`users/${currentUser.uid}/appointments`,id),{status});toast(`Estado actualizado a ${status}`);}catch(err){toast(`Error Firebase: ${err.message}`);setSyncState('error','Error sync');}}
async function deleteAppointment(id){try{await deleteDoc(doc(db,`users/${currentUser.uid}/appointments`,id));toast('Cita borrada');}catch(err){toast(`Error Firebase: ${err.message}`);}}
async function deleteService(id){services=services.filter(s=>s.id!==id);await saveUserSettings();renderServiceOptions();renderServices();toast('Servicio borrado');}
async function saveUserSettings(){await setDoc(doc(db,'users',currentUser.uid),{businessName:settings.businessName,pin:settings.pin,services},{merge:true});}
async function loadUserSettings(){const snap=await getDoc(doc(db,'users',currentUser.uid));if(snap.exists()){const d=snap.data();settings.businessName=d.businessName||settings.businessName;settings.pin=d.pin||settings.pin;services=Array.isArray(d.services)&&d.services.length?d.services:[...fallbackServices];}else{services=[...fallbackServices];await saveUserSettings();}applyBranding();renderServiceOptions();renderServices();}
const showPinStep=()=>{els.loginForm.classList.add('hidden');els.pinScreen.classList.remove('hidden');};
const showLoginStep=()=>{els.pinScreen.classList.add('hidden');els.loginForm.classList.remove('hidden');};
els.registerBtn.addEventListener('click',async()=>{try{setSyncState('loading','Creando acceso');await createUserWithEmailAndPassword(auth,els.loginEmail.value.trim(),els.loginPassword.value);toast('Usuario creado');}catch(err){toast(`Auth error: ${err.message}`);setSyncState('error','Error auth');}});
els.loginForm.addEventListener('submit',async e=>{e.preventDefault();try{setSyncState('loading','Entrando');await signInWithEmailAndPassword(auth,els.loginEmail.value.trim(),els.loginPassword.value);}catch(err){toast(`Auth error: ${err.message}`);setSyncState('error','Error auth');}});
els.pinBtn.addEventListener('click',()=>{if(els.pinInput.value.trim()!==settings.pin){toast('PIN incorrecto');return;}els.authScreen.classList.add('hidden');els.mainShell.classList.remove('hidden');activateView('home');});
els.backToLoginBtn.addEventListener('click',async()=>{try{await signOut(auth);}catch{}});
els.logoutBtn.addEventListener('click',async()=>{try{await signOut(auth);}catch{}});
els.service.addEventListener('change',()=>{const o=els.service.options[els.service.selectedIndex];if(o?.dataset?.price&&!els.appointmentId.value)els.price.value=o.dataset.price;});
els.filterDate.addEventListener('change',renderDashboard);els.quickAddBtn.addEventListener('click',()=>activateView('agenda'));document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>activateView(btn.dataset.view)));els.resetBtn.addEventListener('click',resetAppointmentForm);els.resetServiceBtn.addEventListener('click',resetServiceForm);
els.settingsForm.addEventListener('submit',async e=>{e.preventDefault();settings.businessName=els.businessName.value.trim()||'Nexus Salón';settings.pin=els.businessPin.value.trim()||'2026';try{await saveUserSettings();applyBranding();toast('Configuración guardada');setSyncState('ok','Sync activo');}catch(err){toast(`Error Firebase: ${err.message}`);setSyncState('error','Error sync');}});
els.serviceForm.addEventListener('submit',async e=>{e.preventDefault();const p={id:els.serviceId.value||`srv_${Date.now()}`,name:els.serviceName.value.trim(),price:Number(els.servicePrice.value||0),time:els.serviceTime.value.trim()};if(!p.name||!p.time){toast('Completa el servicio');return;}const idx=services.findIndex(s=>s.id===p.id);if(idx>=0)services[idx]=p;else services.unshift(p);try{await saveUserSettings();renderServiceOptions();renderServices();resetServiceForm();toast('Servicio guardado');setSyncState('ok','Sync activo');}catch(err){toast(`Error Firebase: ${err.message}`);setSyncState('error','Error sync');}});
els.appointmentForm.addEventListener('submit',async e=>{e.preventDefault();const p={clientName:els.clientName.value.trim(),clientPhone:els.clientPhone.value.trim(),service:els.service.value,price:Number(els.price.value||0),date:els.date.value,time:els.time.value,barber:els.barber.value.trim(),status:els.status.value,notes:els.notes.value.trim()};if(!p.clientName||!p.service||!p.date||!p.time){toast('Faltan campos');return;}try{if(els.appointmentId.value){await updateDoc(doc(db,`users/${currentUser.uid}/appointments`,els.appointmentId.value),p);toast('Cita actualizada');}else{await addDoc(collection(db,`users/${currentUser.uid}/appointments`),{...p,createdAt:serverTimestamp()});toast('Cita guardada');}resetAppointmentForm();activateView('home');setSyncState('ok','Sync activo');}catch(err){toast(`Error Firebase: ${err.message}`);setSyncState('error','Error sync');}});
onAuthStateChanged(auth,async user=>{if(!user){currentUser=null;if(unsubAppointments){unsubAppointments();unsubAppointments=null;}appointments=[];services=[];settings={businessName:'Nexus Salón',pin:'2026'};showLoginStep();els.authScreen.classList.remove('hidden');els.mainShell.classList.add('hidden');els.headerUserEmail.textContent='';setSyncState('loading','Sin sesión');return;}currentUser=user;els.headerUserEmail.textContent=user.email||'';setSyncState('loading','Sincronizando');try{await loadUserSettings();showPinStep();unsubAppointments=onSnapshot(collection(db,`users/${user.uid}/appointments`),snapshot=>{appointments=snapshot.docs.map(d=>({id:d.id,...d.data()}));renderDashboard();setSyncState('ok','Sync activo');},error=>{toast(`Firebase error: ${error.message}`);setSyncState('error','Error sync');});}catch(err){toast(`Firebase error: ${err.message}`);setSyncState('error','Error sync');}});
