import { db, collection, addDoc, onSnapshot, doc, updateDoc, serverTimestamp, firebaseReady } from './firebase-config.js';
const $=(id)=>document.getElementById(id);
const els={pinScreen:$('pinScreen'),mainShell:$('mainShell'),pinInput:$('pinInput'),pinBtn:$('pinBtn'),logoutBtn:$('logoutBtn'),appointmentForm:$('appointmentForm'),clientName:$('clientName'),clientPhone:$('clientPhone'),service:$('service'),price:$('price'),date:$('date'),time:$('time'),barber:$('barber'),status:$('status'),notes:$('notes'),filterDate:$('filterDate'),todayCount:$('todayCount'),todayRevenue:$('todayRevenue'),completedCount:$('completedCount'),completedRevenue:$('completedRevenue'),pendingCount:$('pendingCount'),confirmedCount:$('confirmedCount'),noshowCount:$('noshowCount'),timeline:$('timeline'),clientsList:$('clientsList'),servicesList:$('servicesList'),toast:$('toast'),quickAddBtn:$('quickAddBtn'),gotoAgendaBtn:$('gotoAgendaBtn'),resetBtn:$('resetBtn'),installBtn:$('installBtn'),firebaseStatus:$('firebaseStatus'),debugMessage:$('debugMessage')};
const DEMO_PIN='2026'; let appointments=[]; let deferredPrompt=null; const today=new Date().toISOString().slice(0,10); els.date.value=today; els.filterDate.value=today;
const seedAppointments=[{id:'s1',clientName:'Miguel Torres',clientPhone:'787-555-1111',service:'Corte + Barba',price:40,date:today,time:'09:00',barber:'Alex',status:'Confirmada',notes:'Cliente VIP'},{id:'s2',clientName:'Chris Rivera',clientPhone:'787-555-1112',service:'Fade premium',price:30,date:today,time:'10:30',barber:'Tony',status:'Pendiente',notes:''},{id:'s3',clientName:'Javier Cruz',clientPhone:'787-555-1113',service:'Corte premium',price:50,date:today,time:'12:00',barber:'Eliezel',status:'Completada',notes:'Pago cash'}];
const baseServices=[{name:'Corte clásico',price:20,time:'30 min'},{name:'Fade premium',price:30,time:'40 min'},{name:'Barba',price:18,time:'20 min'},{name:'Corte + Barba',price:40,time:'50 min'},{name:'Lavado + estilo',price:22,time:'20 min'},{name:'Corte premium',price:50,time:'60 min'}];
const money=(v)=>new Intl.NumberFormat('es-PR',{style:'currency',currency:'USD'}).format(v||0);
const escapeHtml=(s='')=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function toast(msg){els.toast.textContent=msg;els.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.add('hidden'),3000);}
function setFirebaseStatus(mode,title,text){els.firebaseStatus.className='status-live';if(mode==='connected')els.firebaseStatus.classList.add('connected');if(mode==='error')els.firebaseStatus.classList.add('error');els.firebaseStatus.innerHTML=`<div class="status-dot"></div><div><strong>${escapeHtml(title)}</strong><p>${escapeHtml(text)}</p></div>`;}
function activateView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelector(`#view-${view}`)?.classList.add('active');document.querySelectorAll('.nav-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.view===view));}
document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>activateView(btn.dataset.view)));
els.quickAddBtn.addEventListener('click',()=>activateView('agenda')); els.gotoAgendaBtn.addEventListener('click',()=>activateView('agenda'));
els.pinBtn.addEventListener('click',enterApp); els.pinInput.addEventListener('keydown',(e)=>{if(e.key==='Enter')enterApp();}); els.logoutBtn.addEventListener('click',()=>{sessionStorage.removeItem('nexusSalonPin');els.mainShell.classList.add('hidden');els.pinScreen.classList.remove('hidden');});
function enterApp(){if(els.pinInput.value.trim()!==DEMO_PIN){toast('PIN incorrecto. Aquí no entra nadie por arte místico.');return;}sessionStorage.setItem('nexusSalonPin','ok');els.pinScreen.classList.add('hidden');els.mainShell.classList.remove('hidden');activateView('home');}
if(sessionStorage.getItem('nexusSalonPin')==='ok'){els.pinScreen.classList.add('hidden');els.mainShell.classList.remove('hidden');}
els.service.addEventListener('change',()=>{const option=els.service.options[els.service.selectedIndex]; if(option?.dataset?.price && !els.price.value) els.price.value=option.dataset.price;});
els.resetBtn.addEventListener('click',()=>{els.appointmentForm.reset();els.date.value=today;}); els.filterDate.addEventListener('change',render);
els.appointmentForm.addEventListener('submit',async(e)=>{e.preventDefault();const payload={clientName:els.clientName.value.trim(),clientPhone:els.clientPhone.value.trim(),service:els.service.value,price:Number(els.price.value||0),date:els.date.value,time:els.time.value,barber:els.barber.value.trim(),status:els.status.value,notes:els.notes.value.trim(),createdAt:serverTimestamp()}; if(!payload.clientName||!payload.service||!payload.date||!payload.time){toast('Faltan campos clave. El negocio no corre con suposiciones.');return;} try{await addDoc(collection(db,'appointments'),payload);toast('Cita guardada en Firestore.');}catch(err){console.error(err);els.debugMessage.textContent=`Save error: ${err.message}`;toast(`Error Firebase: ${err.message}`);} els.appointmentForm.reset();els.date.value=today;activateView('home');});
const statusClass=(s='')=>`status-${s.toLowerCase().replace(/\s+/g,'-')}`;
async function updateStatus(id,status){const index=appointments.findIndex(a=>a.id===id);if(index>=0)appointments[index].status=status;if(String(id).startsWith('s')){render();toast(`Estado actualizado a ${status} en demo.`);return;}try{await updateDoc(doc(db,'appointments',id),{status});toast(`Estado actualizado a ${status}.`);}catch(err){console.error(err);els.debugMessage.textContent=`Update error: ${err.message}`;toast(`Error Firebase: ${err.message}`);}render();}
const sortAppointments=(items)=>[...items].sort((a,b)=>`${a.date||''} ${a.time||''}`.localeCompare(`${b.date||''} ${b.time||''}`));
function renderTimeline(items){if(!items.length){els.timeline.innerHTML=`<div class="timeline-meta">No hay citas en esta fecha. Agenda liviana, café pesado.</div>`;return;}els.timeline.innerHTML=items.map(item=>`<article class="timeline-item"><div class="timeline-top"><div><div class="timeline-title">${escapeHtml(item.time||'--:--')} · ${escapeHtml(item.service||'Servicio')}</div><div class="timeline-meta">${escapeHtml(item.clientName||'Cliente')} · ${escapeHtml(item.barber||'Sin asignar')}</div></div><span class="status-chip ${statusClass(item.status)}">${escapeHtml(item.status||'Pendiente')}</span></div><div class="timeline-meta">${escapeHtml(item.clientPhone||'Sin teléfono')} · ${money(item.price||0)}${item.notes?`<br>${escapeHtml(item.notes)}`:''}</div><div class="timeline-actions"><button class="secondary-btn status-btn" data-id="${item.id}" data-status="Completada">Completar</button><button class="secondary-btn status-btn" data-id="${item.id}" data-status="Confirmada">Confirmar</button><button class="secondary-btn status-btn" data-id="${item.id}" data-status="Cancelada">Cancelar</button><button class="secondary-btn status-btn" data-id="${item.id}" data-status="No-show">No-show</button></div></article>`).join(''); document.querySelectorAll('.status-btn').forEach(btn=>btn.addEventListener('click',()=>updateStatus(btn.dataset.id,btn.dataset.status)));}
function renderClients(items){const map=new Map();items.forEach(item=>{const key=`${item.clientName}__${item.clientPhone}`;if(!map.has(key))map.set(key,{name:item.clientName,phone:item.clientPhone,visits:0,spent:0});const row=map.get(key);row.visits+=1;if(!['Cancelada','No-show'].includes(item.status))row.spent+=Number(item.price||0);});const clients=[...map.values()].sort((a,b)=>b.spent-a.spent);els.clientsList.innerHTML=clients.map(c=>`<article class="list-card"><strong>${escapeHtml(c.name||'Cliente')}</strong><div class="timeline-meta">${escapeHtml(c.phone||'Sin teléfono')}</div><div class="timeline-meta">${c.visits} visitas · ${money(c.spent)}</div></article>`).join('')||`<div class="timeline-meta">Aún no hay clientes cargados.</div>`;}
function renderServices(){els.servicesList.innerHTML=baseServices.map(s=>`<article class="list-card"><strong>${escapeHtml(s.name)}</strong><div class="timeline-meta">${money(s.price)} · ${escapeHtml(s.time)}</div></article>`).join('');}
function render(){const selectedDate=els.filterDate.value||today;const ordered=sortAppointments(appointments);const dayItems=ordered.filter(a=>a.date===selectedDate);const completed=dayItems.filter(a=>a.status==='Completada');const pending=dayItems.filter(a=>a.status==='Pendiente');const confirmed=dayItems.filter(a=>a.status==='Confirmada');const noShow=dayItems.filter(a=>a.status==='No-show');const totalRevenue=dayItems.filter(a=>!['Cancelada','No-show'].includes(a.status)).reduce((sum,a)=>sum+Number(a.price||0),0);const completedRevenue=completed.reduce((sum,a)=>sum+Number(a.price||0),0);els.todayCount.textContent=String(dayItems.length);els.todayRevenue.textContent=money(totalRevenue);els.completedCount.textContent=String(completed.length);els.completedRevenue.textContent=money(completedRevenue);els.pendingCount.textContent=String(pending.length);els.confirmedCount.textContent=String(confirmed.length);els.noshowCount.textContent=String(noShow.length);renderTimeline(dayItems);renderClients(ordered);renderServices();}
appointments=[...seedAppointments]; render(); setFirebaseStatus('loading','Conectando a Firebase','Lectura directa de appointments sin índice compuesto.');
if(firebaseReady && db){try{const liveCollection=collection(db,'appointments');onSnapshot(liveCollection,(snapshot)=>{const cloudItems=snapshot.docs.map(d=>({id:d.id,...d.data()}));appointments=cloudItems.length?cloudItems:[...seedAppointments];render();setFirebaseStatus('connected','Firebase conectado','Firestore está respondiendo y V4 no depende del índice compuesto.');els.debugMessage.textContent='Firestore online y lectura simplificada activa.';},(error)=>{console.error(error);appointments=[...seedAppointments];render();setFirebaseStatus('error','Error de Firestore',error.message);els.debugMessage.textContent=error.message;toast(`Firebase error: ${error.message}`);});}catch(error){console.error(error);setFirebaseStatus('error','Error al iniciar Firebase',error.message);els.debugMessage.textContent=error.message;}} else {setFirebaseStatus('error','Firebase no inicializado','La configuración no cargó correctamente.');els.debugMessage.textContent='Firebase no inicializado.';}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));}
window.addEventListener('beforeinstallprompt',(e)=>{e.preventDefault();deferredPrompt=e;els.installBtn.classList.remove('hidden');});
els.installBtn.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;els.installBtn.classList.add('hidden');});